language: python
python: 2.7
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
branches:
    only:
        - master

env:
    - TOX_ENV=py27
    - TOX_ENV=pep8

install:
  - pip install codecov coverage tox
  - python setup.py --version
  - pip install -e.[dev]

script:
  - coverage run --branch --source txdocumint $(type -p py.test) txdocumint
  - coverage report -m
  - tox -e "${TOX_ENV}"

after_success:
  - codecov

notifications:
  email: false
